DEBUG: true
theme: default

mysql:
    dsn: yoomall:yoomall@tcp(127.0.0.1:3306)/yoomall?charset=utf8mb4&parseTime=True&loc=Local
postgres:
    # dsn: postgres://yoomall:yoomall@127.0.0.1:5432/yoomall?sslmode=disable
    dsn: postgres://default:0ZGuIPA5Yytz@ep-young-glade-a46ojcba.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require

storage_path: ./storage

dtk: 
    app_key: xx
    app_secret: xx
    app_url: https://openapi.dataoke.com/api/

jutuike:
    pub_id: xx
    api_key: xx
    jtk_url: http://api.jutuike.com/


vite:
    url: http://127.0.0.1:5173/
    debug: true
    build_dir: ./public 


site:
    title: "Ship It 1 Day"
    description: "ship1d.com is helping your build your business."
    keywords: "YooMall, Online Shopping, YooMall, YooMall, YooMall"
    author: "YooMall"
    favicon: "/images/favicon.ico"
    logo: "/images/logo.png"